#! /usr/bin/env python
import argparse
import os.path
import snakemake
import sys


thisdir = os.path.abspath(os.path.dirname(__file__))


def main():
    parser = argparse.ArgumentParser(description='run snakemake workflows for spacegraphcats', usage='''run <configfile.json> [<target>]

Run snakemake workflows for spacegraphcats, using the given config file.

Targets:

   build            - builds catlas
   searchquick      - do a quick search (only a few files)
   search           - do a full search for this data set (many files)

For a quickstart, run this:

   snakeconf/run snakeconf/dory-test.json searchquick

from the main spacegraphcats directory.
.
''')

    parser.add_argument('configfile')
    parser.add_argument('target', nargs='?', default='build')
    parser.add_argument('-n', '--dry-run', action='store_true')
    parser.add_argument('--nolock', action='store_true')
    args = parser.parse_args()

    snakefile = os.path.join(thisdir, 'Snakefile')
    if not os.path.exists(snakefile):
        sys.stderr.write('Error: cannot find Snakefile at {}\n'.format(snakefile))
        sys.exit(-1)

    if os.path.exists(args.configfile) and not os.path.isdir(args.configfile):
        configfile = args.configfile
    else:
        for suffix in ('', '.json'):
            tryfile = os.path.join(thisdir, args.configfile + suffix)
            if os.path.exists(tryfile) and not os.path.isdir(tryfile):
                sys.stderr.write('Found configfile at {}\n'.format(tryfile))
                configfile = tryfile
                break

    if not os.path.exists(configfile):
        sys.stderr.write('Error: cannot find configfile {}\n'.format(configfile))
        sys.exit(-1)

    status = snakemake.snakemake(snakefile, configfile=configfile,
                                 targets=[args.target], printshellcmds=True,
                                 dryrun=args.dry_run,
                                 lock=not args.nolock)

    return status


if __name__ == '__main__':
    sys.exit(main())
