name: spacegraphcats
channels:
    - conda-forge
    - bioconda
    - defaults
dependencies:
    - python>=3.12,<3.14
    - bcalm=2.2.3
    - snakemake-minimal
    - screed>=1.1,<2
    - numpy
    - pytest
    - sortedcontainers=2.1.0
    - click>=8.1.2,<9
    - pyflakes
    - bbhash>=0.6.0
    - sourmash>=4.9.4,<5
    - mamba
