import sqlite3
import os

from .pytest_utils import pkg_file
from spacegraphcats.search import search_utils


def test_get_contig_by_id():
    testdata = pkg_file("tests/test-data/catlas.dory_k21")
    db_filename = os.path.join(testdata, "bcalm.unitigs.db")
    db = sqlite3.connect(db_filename)

    records = list(search_utils.get_contigs_by_cdbg_sqlite(db, [118]))
    assert len(records) == 1
    record = records[0]
    assert record.name == "118"
    print(record.sequence)
    assert (
        record.sequence
        == "AGACCAACCTTTAGCCTATTCAAGACGAGTGTACTTAGAGCTTCTCCATCAACATCTTCAGCGATTATGACCAAAGGCTTACGGTGAGCATTGGCAATTTCAAGAGCAGGTACAATGGACTGGATACTAGAAATTTTCTTTTCACTCAACAGAACATAGGCATCCTGGAATTCACATTTCTGACCTTTTGATGTATTAATAAAGTATGGAGAAATATAGCCTCGATCAAACTTCATGCCTTCAATAATTTCTAATTCATCATTCAGTGTTTTTCCATCCTTTACTGTGATGACACCCTTTCTTCCAACTTTTTTCATTGCATCAGAGATGATATTGCCAATTTCTTTGTCTCCGTTTGCAGAAATCGTAGCAACCTGTGCAATTTCTTCAGGGGTGGTCACAGGTTTAGACTGCTTTTTAAGTTCAGCAATTACAGCATCAACAGCTAACATCACACCTCTCCTGATTTCCACTGGATTAGCACCTTTGCTAATCTTCTCGAAGCCTTCCTTGGCTATAGAGCGTGCCAGTACAGTAGCAGTGGTAGTGCCATCCCCAGCTTCTTCATTTGTGTTATTGGCAACATCTTGAACAAGTTTAGCTCCAATGTTCTTGTATTTATCTTTTAAGTCAATTGACTTTGCAACAGTCACACCATCTTTTGTTACTTTGGGACTTCCCCAACTCTGCTCAATAATCACTGTTCTTCCCTTTGGCCCCATTGTAACGGCCACAGCATCGGCTAAAAGGTCTACACCTTGAAGCATTAAGGCTCGGGCATCTGCACCAAATTTTACATCTTTGGCATAAGCCCGAGTGAGATGAGGAGCCAGTACCCTGGACACCGGTCTCAT"
    )
