#! /usr/bin/env python
"""
Execution script for snakemake workflows for spacegraphcats.
"""
import sys, os.path

thisdir = os.path.abspath(os.path.dirname(__file__))
sys.path.insert(0, os.path.join(thisdir, '../'))
from spacegraphcats.__main__ import main

sys.exit(main())
