name: Run tests

on:
  push:
    branches: [latest]
  pull_request:
  schedule:
    - cron: "0 0 * * *" # daily

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        python: [3.8]

    name: Python ${{ matrix.python }}

    steps:
      - name: checkout
        uses: actions/checkout@v4

      # per https://github.com/conda-incubator/setup-miniconda#caching-environments
      - name: Setup Mambaforge
        uses: conda-incubator/setup-miniconda@v2
        with:
          miniforge-variant: Mambaforge
          miniforge-version: latest
          activate-environment: anaconda-client-env
          use-mamba: true
          python-version: ${{ matrix.python }}

      - name: Get Date
        id: get-date
        run: echo "today=$(/bin/date -u '+%Y%m%d')" >> $GITHUB_OUTPUT
        shell: bash

      - name: Cache Conda env
        uses: actions/cache@v4
        with:
          path: ${{ env.CONDA }}/envs
          key:
            conda-${{ runner.os }}--${{ runner.arch }}--${{
            steps.get-date.outputs.today }}-${{
            hashFiles('etc/example-environment-caching.yml') }}-${{ env.CACHE_NUMBER
            }}
        env:
          # Increase this value to reset cache if etc/example-environment.yml has not changed
          CACHE_NUMBER: 0
          id: cache

      - name: Update environment
        run:
          mamba env update -n anaconda-client-env -f environment.yml
        if: steps.cache.outputs.cache-hit != 'true'

      - name: Show Python version
        shell: bash -el {0}
        run: python -V

      - name: Conda info
        shell: bash -el {0}
        run: conda info

      - name: Conda list
        shell: bash -el {0}
        run: conda list

      - name: Install test dependencies
        shell: bash -el {0}
        run: python -m pip install pytest-cov black flake8

      - name: Install Cython and other dev deps
        shell: bash -el {0}
        run: python -m pip install Cython setuptools_scm_git_archive

      - name: Install sgc
        shell: bash -el {0}
        run: python -m pip install -e .

#      - run: pip check

      - run: make black
        shell: bash -el {0}

      - run: make flakes
        shell: bash -el {0}

      - run: pytest tests --cov=.
        shell: bash -el {0}

      - run: make twofoo-test
        shell: bash -el {0}

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
