name: Run tests

on:
  push:
    branches: [latest]
  pull_request:
  schedule:
    - cron: "0 0 * * *" # daily

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python: [3.8]

    name: Python ${{ matrix.python }}

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}

      - run: pip install -U pip setuptools
      - run: pip install -U Cython

      - name: Setup conda
        uses: s-weigand/setup-conda@v1
        with:
            activate-conda: false
      - run: conda install -c conda-forge -c bioconda bcalm mamba

      - name: Install Python dependencies
        run: pip install -U -r requirements.txt

      - name: Install coverage dependencies
        run: pip install pytest-cov

      - name: Build
        run: python setup.py build_ext --inplace

      - name: Install sgc
        run: pip install -e .

      - run: make black
      - run: make flakes
      - run: make lint

      - run: pytest tests --cov=.
      - run: make twofoo-test

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
